
spring:
  application:
    name: mpai.demo
    version: 1
  datasource:
    url: jdbc:h2:mem:mpaidb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console


#spring.application.name=mpai.demo
#spring.application.version=2
server:
  servlet:
    context-path: /mpai-spring-mvc